# NumPy & Pandas Practice Notebook
## Dataset: AI Impact on Jobs (2010–2025)

In [5]:
# TODO: Import NumPy and Pandas libraries
import pandas as pd 
import numpy  as np

In [7]:
# TODO: Load the CSV file into a pandas DataFrame
# TODO: Display the first 5 rows

df= pd.read_csv(r'C:\Users\Pratik\Downloads\ai_impact_jobs_2010_2025.csv')
df.head()

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
0,836b4774-702e-49ef-93d3-2f255ce1e910,2018,Brazil,South America,London,NextGen Technologies,Small,Education,Policy Analyst,Lead,...,0.81,"Research, Project Management, Business Analysis",reinforcement learning,61586,12.68,0.11,True,Low,14,Growing
1,43699e93-7b15-4728-a4c6-9e41ff438a25,2015,UAE,Middle East,Singapore,Future Solutions,Medium,Energy,Data Scientist,Executive,...,0.04,"Research, SQL, Business Analysis, Python, Clou...",NaN,62045,-3.98,0.71,False,High,19,Emerging
2,fc9d1854-3cbf-4bab-90df-77304dfc59df,2016,Nepal,South Asia,Sydney,Future Analytics,Startup,Finance,Product Manager,Junior,...,0.15,"Statistics, Project Management, Cloud Computin...",NaN,27035,3.55,0.86,False,High,2,Emerging
3,05c1c7d3-2add-4919-91eb-f6c78bfe23d1,2015,Spain,Europe,Nairobi,Global Technologies,Large,Government,Data Scientist,Mid,...,0.19,"Cloud Computing, SQL, Project Management, Comm...",NaN,72894,-2.80,0.70,False,Low,15,Emerging
4,5e739937-d1b0-44d7-935c-7ebb3fc1f6e8,2014,Taiwan,East Asia,Sydney,Future Technologies,Small,Manufacturing,ML Engineer,Lead,...,0.11,"SQL, Python, Communication, Software Engineeri...",NaN,57215,0.85,0.87,False,High,13,Emerging

In [8]:
# TODO: Check basic information about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   job_id                              5000 non-null   object
 1   posting_year                        5000 non-null   int64
 2   country                             5000 non-null   object
 3   region                              5000 non-null   object
 4   city                                5000 non-null   object
 5   company_name                        5000 non-null   object
 6   company_size                        5000 non-null   object
 7   industry                            5000 non-null   object
 8   job_title                           5000 non-null   object
 9   seniority_level                     5000 non-null   object
 10  ai_mentioned                        5000 non-null   bool
 11  ai_keywords                         1623 non-null   object
 12  ai_intensity_score                  5000 non-null   float64
 13  core_skills                         5000 non-null   object
 14  ai_skills                           1623 non-null   object
 15  salary_usd                          5000 non-null   int64
 16  salary_change_vs_prev_year_percent  5000 non-null   float64
 17  automation_risk_score               5000 non-null   float64
 18  reskilling_required                 5000 non-null   bool
 19  ai_job_displacement_risk            5000 non-null   object
 20  job_description_embedding_cluster   5000 non-null   int64
 21  industry_ai_adoption_stage          5000 non-null   object
dtypes: bool(2), float64(3), int64(3), object(14)
memory usage: 791.1+ KB

In [9]:
# TODO: Find total number of rows and columns
df.shape

(5000, 22)

In [11]:
# TODO: Display all column names
df.columns

Index(['job_id', 'posting_year', 'country', 'region', 'city', 'company_name',
       'company_size', 'industry', 'job_title', 'seniority_level',
       'ai_mentioned', 'ai_keywords', 'ai_intensity_score', 'core_skills',
       'ai_skills', 'salary_usd', 'salary_change_vs_prev_year_percent',
       'automation_risk_score', 'reskilling_required',
       'ai_job_displacement_risk', 'job_description_embedding_cluster',
       'industry_ai_adoption_stage'],
      dtype='object')

In [12]:
# TODO: Generate descriptive statistics

df.describe()

,posting_year,ai_intensity_score,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,job_description_embedding_cluster
count,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000
mean,2017.519400,0.287312,63096.18480,3.015192,0.586176,9.473000
std,4.638569,0.291377,31431.27151,5.968729,0.250007,5.748763
min,2010.000000,0.000000,15321.00000,-5.000000,0.100000,0.000000
25%,2013.000000,0.070000,36575.50000,-1.580000,0.330000,4.000000
50%,2017.000000,0.150000,60909.50000,1.720000,0.670000,10.000000
75%,2022.000000,0.520000,81811.75000,5.385000,0.790000,14.000000
max,2025.000000,0.950000,161547.00000,17.980000,0.900000,19.000000

In [14]:
# TODO: Check missing values in each column
df.isna().sum()

job_id                                   0
posting_year                             0
country                                  0
region                                   0
city                                     0
company_name                             0
company_size                             0
industry                                 0
job_title                                0
seniority_level                          0
ai_mentioned                             0
ai_keywords                           3377
ai_intensity_score                       0
core_skills                              0
ai_skills                             3377
salary_usd                               0
salary_change_vs_prev_year_percent       0
automation_risk_score                    0
reskilling_required                      0
ai_job_displacement_risk                 0
job_description_embedding_cluster        0
industry_ai_adoption_stage               0
dtype: int64

In [15]:
# TODO: Handle missing values appropriately

df.dropna()

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
0,836b4774-702e-49ef-93d3-2f255ce1e910,2018,Brazil,South America,London,NextGen Technologies,Small,Education,Policy Analyst,Lead,...,0.81,"Research, Project Management, Business Analysis",reinforcement learning,61586,12.68,0.11,True,Low,14,Growing
5,3eaa8f95-6ada-4e08-ad17-ca924707d66f,2022,Colombia,South America,London,Future Analytics,Enterprise,Government,ML Engineer,Senior,...,0.77,"Cloud Computing, Research, Data Analysis",deep learning,67379,8.47,0.29,True,High,3,Growing
8,2e7cd904-6aaf-4138-9464-1ad4971c25bf,2017,India,South Asia,Bangalore,Prime Technologies,Startup,Education,Policy Analyst,Junior,...,0.44,"Project Management, Software Engineering, Busi...",deep learning,29117,-1.70,0.25,True,High,13,Growing
12,e39cdd94-1247-4380-89db-56c8a4b84f06,2017,China,East Asia,Singapore,Global Systems,Enterprise,Tech,Operations Manager,Lead,...,0.53,"SQL, Research, Project Management","NLP, deep learning, reinforcement learning",90257,1.72,0.19,True,High,8,Growing
14,21f7cb94-8074-4252-b5cc-aff4ef10f046,2018,Pakistan,South Asia,Berlin,Future Technologies,Large,Agriculture,Operations Manager,Lead,...,0.75,"Research, Python, SQL, Communication, Statisti...",machine learning,38150,5.57,0.20,True,High,1,Growing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,1c71e984-bc39-48df-8582-74328ff6d1a0,2021,Italy,Europe,Nairobi,NextGen Solutions,Large,Government,Operations Manager,Junior,...,0.50,"Communication, Cloud Computing, Python, Data A...","NLP, LLMs",124048,10.01,0.29,True,High,17,Growing
4992,1a7b5ce7-8605-44e3-a2f1-723c6e480df4,2015,China,East Asia,Berlin,Global Solutions,Enterprise,Agriculture,Systems Engineer,Lead,...,0.77,"Software Engineering, Business Analysis, Cloud...","NLP, deep learning, MLOps, reinforcement learning",86256,-3.39,0.36,True,Medium,12,Emerging
4994,ff148884-e18a-4a5a-b899-241eebf32b99,2025,Pakistan,South Asia,Tokyo,NextGen Technologies,Startup,Retail,ML Engineer,Mid,...,0.53,"Software Engineering, Communication, Project M...",machine learning,37739,8.25,0.38,True,High,7,Growing
4998,ad529cef-b22e-4e7d-82fd-98fc06d61596,2016,Sweden,Europe,Sydney,NextGen Systems,Enterprise,Energy,AI Researcher,Junior,...,0.87,"SQL, Research, Cloud Computing, Communication,...","computer vision, MLOps",107897,-0.23,0.33,True,Low,14,Emerging
4999,79d26161-8cc1-4d98-ab0d-3ebea91f2a1b,2024,India,South Asia,Tokyo,Future Analytics,Enterprise,Tech,Software Engineer,Executive,...,0.56,"Software Engineering, Project Management, Busi...",LLMs,35755,11.00,0.10,True,Low,11,Mature

In [18]:
# TODO: Identify unique values in categorical columns

df.select_dtypes('object').nunique()

job_id                        5000
country                         44
region                           9
city                            14
company_name                    16
company_size                     5
industry                         9
job_title                       10
seniority_level                  6
ai_keywords                    617
core_skills                   4162
ai_skills                      617
ai_job_displacement_risk         3
industry_ai_adoption_stage       3
dtype: int64

In [27]:
# TODO: Check and convert data types if needed
# df.info()

df.dtypes

job_id                                 object
posting_year                            int64
country                                object
region                                 object
city                                   object
company_name                           object
company_size                           object
industry                               object
job_title                              object
seniority_level                        object
ai_mentioned                             bool
ai_keywords                            object
ai_intensity_score                    float64
core_skills                            object
ai_skills                              object
salary_usd                              int64
salary_change_vs_prev_year_percent    float64
automation_risk_score                 float64
reskilling_required                      bool
ai_job_displacement_risk               object
job_description_embedding_cluster       int64
industry_ai_adoption_stage             object
dtype: object

In [30]:
# TODO: Sort dataset based on Year

df.sort_values("posting_year")

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
3573,6db034d3-37f3-4050-bb11-3588dc6741f7,2010,Argentina,South America,London,Global Solutions,Small,Government,Data Scientist,Junior,...,0.11,"Data Analysis, Statistics, Software Engineerin...",NaN,33694,4.69,0.75,False,Medium,2,Emerging
4160,d5f11a67-b06e-491e-9ff2-cb2621367bfe,2010,United States,North America,Paris,Prime Technologies,Small,Energy,Business Analyst,Intern,...,0.10,"Data Analysis, SQL, Project Management, Cloud ...",NaN,63767,-2.77,0.86,False,Medium,15,Emerging
1008,951b2915-6a70-4d87-a22e-ebe13ed65c0a,2010,Taiwan,East Asia,Bangalore,NextGen Solutions,Enterprise,Energy,AI Researcher,Lead,...,0.12,"Project Management, Python, Data Analysis, Bus...",NaN,60272,-0.61,0.60,False,High,2,Emerging
4619,96e2576c-cac4-44be-be38-b8cb9937e958,2010,Jordan,Middle East,Dubai,Global Technologies,Startup,Healthcare,ML Engineer,Mid,...,0.12,"SQL, Communication, Data Analysis, Business An...",NaN,54103,-4.58,0.80,False,High,1,Emerging
3537,b4e60d91-6d90-4c75-b50f-7bf500645691,2010,India,South Asia,Sydney,Future Solutions,Large,Finance,AI Researcher,Intern,...,0.02,"Data Analysis, Project Management, Python, Sof...",NaN,18183,1.26,0.86,False,Low,9,Emerging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1564,59519399-5729-4d90-a291-a61a48502973,2025,Japan,East Asia,Tokyo,Global Analytics,Startup,Education,Product Manager,Lead,...,0.89,"Python, Communication, Project Management, Bus...","computer vision, machine learning",128273,11.55,0.15,True,Low,16,Growing
3674,cb0f3fff-aeb8-4f56-80cb-bc359c70e35f,2025,Egypt,Africa,Sydney,Future Solutions,Medium,Government,Research Scientist,Lead,...,0.45,"Business Analysis, Project Management, Cloud C...","NLP, machine learning, computer vision",40082,15.85,0.36,True,High,9,Growing
4656,e1ca3603-2c70-4cb4-a2bb-49b76e3c6ee8,2025,Vietnam,Southeast Asia,New York,Global Technologies,Small,Education,Product Manager,Mid,...,0.14,"SQL, Cloud Computing, Data Analysis, Python, R...",NaN,42208,2.65,0.65,False,Low,13,Growing
3582,df764b92-79f8-40b1-b165-8b9a02fbfa8a,2025,Mexico,North America,Dubai,Prime Technologies,Medium,Finance,Product Manager,Executive,...,0.91,"Research, Project Management, Statistics, Data...","NLP, LLMs",149448,8.76,0.22,True,High,19,Mature
3819,25676a5f-058d-4ec6-84e6-84e43773c6dc,2025,Australia,Oceania,Singapore,NextGen Analytics,Startup,Energy,Systems Engineer,Intern,...,0.12,"SQL, Communication, Data Analysis, Research",NaN,83783,-0.22,0.73,False,Medium,19,Growing

In [32]:
# TODO: Filter records where Year > 2020

df[df['posting_year'] > 2020]

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
5,3eaa8f95-6ada-4e08-ad17-ca924707d66f,2022,Colombia,South America,London,Future Analytics,Enterprise,Government,ML Engineer,Senior,...,0.77,"Cloud Computing, Research, Data Analysis",deep learning,67379,8.47,0.29,True,High,3,Growing
9,bcf3fde0-b3e8-457f-9b90-fa1716e92bae,2023,Sri Lanka,South Asia,Seoul,Global Technologies,Startup,Government,AI Researcher,Junior,...,0.20,"Data Analysis, Business Analysis, Communicatio...",NaN,24450,-0.97,0.70,False,Low,14,Growing
17,9357ad9b-1bec-4d4f-8f1f-f16f11d59302,2022,Nepal,South Asia,Bangalore,Global Systems,Medium,Agriculture,Research Scientist,Senior,...,0.02,"Statistics, Business Analysis, SQL, Project Ma...",NaN,31038,-3.21,0.89,False,Low,8,Growing
18,09bdb9b7-3e71-4e27-a2d4-1373b104850f,2023,Mexico,North America,Singapore,Prime Systems,Enterprise,Tech,Product Manager,Lead,...,0.11,"SQL, Cloud Computing, Research, Statistics, Pr...",NaN,103705,2.42,0.80,False,Medium,12,Mature
22,8dd1bce3-ab19-4c1f-a886-a3eea77a7577,2025,Jordan,Middle East,Lagos,NextGen Technologies,Medium,Education,Software Engineer,Senior,...,0.58,"Statistics, Research, Software Engineering, Pr...","computer vision, NLP, MLOps",102722,6.80,0.17,True,Medium,12,Growing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,1c71e984-bc39-48df-8582-74328ff6d1a0,2021,Italy,Europe,Nairobi,NextGen Solutions,Large,Government,Operations Manager,Junior,...,0.50,"Communication, Cloud Computing, Python, Data A...","NLP, LLMs",124048,10.01,0.29,True,High,17,Growing
4991,c4f14b95-7fc7-433a-b628-920eb99866f6,2021,South Korea,East Asia,Bangalore,Future Solutions,Startup,Retail,Software Engineer,Junior,...,0.19,"Data Analysis, Cloud Computing, Project Manage...",NaN,64277,-0.67,0.77,False,Medium,4,Growing
4994,ff148884-e18a-4a5a-b899-241eebf32b99,2025,Pakistan,South Asia,Tokyo,NextGen Technologies,Startup,Retail,ML Engineer,Mid,...,0.53,"Software Engineering, Communication, Project M...",machine learning,37739,8.25,0.38,True,High,7,Growing
4995,45aa223b-3ed6-4574-bd07-294a1443c02b,2022,Singapore,Southeast Asia,Bangalore,Prime Analytics,Enterprise,Education,ML Engineer,Intern,...,0.12,"SQL, Project Management, Data Analysis",NaN,41317,4.62,0.88,False,Low,17,Growing
4999,79d26161-8cc1-4d98-ab0d-3ebea91f2a1b,2024,India,South Asia,Tokyo,Future Analytics,Enterprise,Tech,Software Engineer,Executive,...,0.56,"Software Engineering, Project Management, Busi...",LLMs,35755,11.00,0.10,True,Low,11,Mature

In [36]:
df['ai_job_displacement_risk'].unique()

df[df['ai_job_displacement_risk']=='High']

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
1,43699e93-7b15-4728-a4c6-9e41ff438a25,2015,UAE,Middle East,Singapore,Future Solutions,Medium,Energy,Data Scientist,Executive,...,0.04,"Research, SQL, Business Analysis, Python, Clou...",NaN,62045,-3.98,0.71,False,High,19,Emerging
2,fc9d1854-3cbf-4bab-90df-77304dfc59df,2016,Nepal,South Asia,Sydney,Future Analytics,Startup,Finance,Product Manager,Junior,...,0.15,"Statistics, Project Management, Cloud Computin...",NaN,27035,3.55,0.86,False,High,2,Emerging
4,5e739937-d1b0-44d7-935c-7ebb3fc1f6e8,2014,Taiwan,East Asia,Sydney,Future Technologies,Small,Manufacturing,ML Engineer,Lead,...,0.11,"SQL, Python, Communication, Software Engineeri...",NaN,57215,0.85,0.87,False,High,13,Emerging
5,3eaa8f95-6ada-4e08-ad17-ca924707d66f,2022,Colombia,South America,London,Future Analytics,Enterprise,Government,ML Engineer,Senior,...,0.77,"Cloud Computing, Research, Data Analysis",deep learning,67379,8.47,0.29,True,High,3,Growing
8,2e7cd904-6aaf-4138-9464-1ad4971c25bf,2017,India,South Asia,Bangalore,Prime Technologies,Startup,Education,Policy Analyst,Junior,...,0.44,"Project Management, Software Engineering, Busi...",deep learning,29117,-1.70,0.25,True,High,13,Growing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,307053d3-3878-4a94-876d-1b521ca14e19,2025,New Zealand,Oceania,Singapore,NextGen Solutions,Medium,Tech,Software Engineer,Lead,...,0.09,"Cloud Computing, Statistics, Data Analysis",NaN,81868,-2.79,0.68,False,High,14,Mature
4986,14eef4a1-2827-426f-b3c8-3bb810516a06,2025,South Korea,East Asia,Tokyo,Prime Technologies,Small,Agriculture,Data Scientist,Senior,...,0.95,"Software Engineering, Communication, Research,...","computer vision, NLP, LLMs, reinforcement lear...",106824,12.19,0.39,True,High,16,Growing
4987,2aba5217-532a-409c-a8e3-2e329e99c427,2013,Spain,Europe,Singapore,Prime Solutions,Enterprise,Healthcare,Data Scientist,Junior,...,0.06,"Business Analysis, Software Engineering, Commu...",NaN,58320,-4.01,0.62,False,High,18,Emerging
4990,1c71e984-bc39-48df-8582-74328ff6d1a0,2021,Italy,Europe,Nairobi,NextGen Solutions,Large,Government,Operations Manager,Junior,...,0.50,"Communication, Cloud Computing, Python, Data A...","NLP, LLMs",124048,10.01,0.29,True,High,17,Growing
4994,ff148884-e18a-4a5a-b899-241eebf32b99,2025,Pakistan,South Asia,Tokyo,NextGen Technologies,Startup,Retail,ML Engineer,Mid,...,0.53,"Software Engineering, Communication, Project M...",machine learning,37739,8.25,0.38,True,High,7,Growing

In [39]:
# TODO: Group data by Year and calculate averages

df.groupby("posting_year")['salary_usd'].mean()

posting_year
2010    47536.159021
2011    47875.792517
2012    47403.283871
2013    50797.125767
2014    54188.724684
2015    55694.006410
2016    56010.356913
2017    57176.445902
2018    65347.595745
2019    65798.114804
2020    69295.197368
2021    70352.906149
2022    76838.089744
2023    77788.943574
2024    82714.390476
2025    83770.201835
Name: salary_usd, dtype: float64

In [41]:
df.groupby('posting_year').mean(numeric_only=True)

,ai_mentioned,ai_intensity_score,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,job_description_embedding_cluster
posting_year,,,,,,,
2010,0.103976,0.158165,47536.159021,0.091437,0.695352,0.103976,9.314985
2011,0.098639,0.155306,47875.792517,-0.016939,0.708571,0.098639,9.472789
2012,0.077419,0.141935,47403.283871,0.250258,0.708000,0.077419,9.003226
2013,0.095092,0.157883,50797.125767,-0.141871,0.704387,0.095092,9.315951
2014,0.186709,0.205981,54188.724684,-0.122563,0.654747,0.186709,9.427215
2015,0.169872,0.196635,55694.006410,0.266282,0.667949,0.169872,9.461538
2016,0.135048,0.184180,56010.356913,-0.259839,0.680225,0.135048,9.308682
2017,0.173770,0.200230,57176.445902,0.317475,0.658721,0.173770,9.740984
2018,0.372340,0.320957,65347.595745,4.444397,0.561135,0.372340,9.985816
2019,0.350453,0.299789,65798.114804,3.824381,0.568489,0.350453,9.534743
2020,0.375000,0.319046,69295.197368,4.670362,0.559211,0.375000,9.759868
2021,0.414239,0.332524,70352.906149,4.548641,0.538803,0.414239,9.203883
2022,0.618590,0.459071,76838.089744,7.084006,0.440064,0.618590,9.733974
2023,0.636364,0.480219,77788.943574,7.224295,0.429436,0.636364,9.247649
2024,0.679365,0.485619,82714.390476,7.961333,0.405079,0.679365,9.815873
2025,0.688073,0.489450,83770.201835,7.927370,0.408318,0.688073,9.318043

In [ ]:
# TODO: Convert a numerical column to NumPy array

In [ ]:
# TODO: Perform NumPy operations (mean, max, min)

In [ ]:
# TODO: Find correlation between numerical columns

In [ ]:
# TODO: Create a new feature based on job impact

In [ ]:
# TODO: Count values in the new feature

In [ ]:
# TODO: Save the processed dataset to a new CSV file